// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package mysqlstore

import (
	"database/sql"
)

type Habit struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
}
