// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package mysqlstore

import (
	"context"
	"database/sql"
)

const creatHabit = `-- name: CreatHabit :execresult
INSERT INTO habits (name)
VALUES (?)
`

func (q *Queries) CreatHabit(ctx context.Context, name string) (sql.Result, error) {
	return q.db.ExecContext(ctx, creatHabit, name)
}

const listHabits = `-- name: ListHabits :many
SELECT id, name, created_at FROM habits
ORDER BY created_at DESC
`

func (q *Queries) ListHabits(ctx context.Context) ([]Habit, error) {
	rows, err := q.db.QueryContext(ctx, listHabits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Habit
	for rows.Next() {
		var i Habit
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
